# Generated by Django 4.2.20 on 2025-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eszkoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megnevezes', models.CharField(max_length=255)),
                ('gyariszam', models.CharField(max_length=55)),
            ],
        ),
    ]
