# Generated by Django 4.2.20 on 2025-05-06 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eszkozkezelo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kepek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kep', models.ImageField(upload_to='kepek/')),
                ('keszitesIdeje', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mozgastipusok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megnevezes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Szemely',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megnevezes', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='beszerzesiIdo',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='selejtezesiIdo',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='tartozek',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='tartozek_eszkoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eszkozkezelo_app.eszkoz'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='gyariszam',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Mozgas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mozgasIdo', models.DateField(default=datetime.date.today)),
                ('honnan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mozgasok_honnan', to='eszkozkezelo_app.szemely')),
                ('hova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mozgasok_hova', to='eszkozkezelo_app.szemely')),
                ('mozgastipus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.mozgastipusok')),
            ],
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='holvanId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.szemely'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='kep_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.kepek'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='tipus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.tipus'),
            preserve_default=False,
        ),
    ]
