# Generated by Django 4.2.20 on 2025-05-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eszkozkezelo_app', '0002_kepek_mozgastipusok_szemely_tipus_eszkoz_aktiv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beszallito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beszallitoNev', models.CharField(max_length=50)),
                ('beszallitoCim', models.CharField(max_length=50)),
                ('beszallitoContatkt', models.CharField(max_length=50)),
                ('beszallitoTel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='garanciaIdo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eszkoz',
            name='beszallito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.beszallito'),
            preserve_default=False,
        ),
    ]
