# Generated by Django 4.2.20 on 2025-05-07 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eszkozkezelo_app', '0003_beszallito_eszkoz_garanciaido_eszkoz_beszallito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beszallito',
            name='beszallitoContatkt',
        ),
        migrations.AddField(
            model_name='beszallito',
            name='beszallitoKontatkt',
            field=models.CharField(default=1, help_text='Beszállító kontatkt személy neve', max_length=50, verbose_name='Beszállító kontatkt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beszallito',
            name='beszallitoCim',
            field=models.CharField(help_text='Beszállító pontos címe', max_length=50, verbose_name='Beszállító címe'),
        ),
        migrations.AlterField(
            model_name='beszallito',
            name='beszallitoNev',
            field=models.CharField(help_text='Beszállító elnevezése ', max_length=50, verbose_name='Beszállító neve'),
        ),
        migrations.AlterField(
            model_name='beszallito',
            name='beszallitoTel',
            field=models.CharField(help_text='Beszállító kontatkt személy telefonszáma', max_length=50, verbose_name='Beszállító telefon'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='aktiv',
            field=models.BooleanField(default=True, help_text='Kiadható még az eszköz', verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='beszerzesiIdo',
            field=models.DateField(auto_now_add=True, help_text='Beszerzés időpontja ( asz eszköz felvétel időpontja)', verbose_name='Beszerzés ideje'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='garanciaIdo',
            field=models.IntegerField(help_text='Garancia időtartama hónapokban', verbose_name='Garancia idő'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='gyariszam',
            field=models.CharField(help_text='Az esköz gyártási száma', max_length=60, verbose_name='Gyári szám'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='megnevezes',
            field=models.CharField(help_text='Az esköz pontos típuselnevezése', max_length=255, verbose_name='Eszköz elnevezése'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='selejtezesiIdo',
            field=models.DateField(default=datetime.date.today, help_text='Mikor került selejtezésre az esköz', verbose_name='Selejtezési idő'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='tartozek',
            field=models.BooleanField(help_text='Ez az eszköz valamely másik eszköz tartozéka - beépítésre került', verbose_name='Tartozék'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='tartozek_eszkoz',
            field=models.ForeignKey(blank=True, help_text='Melyik eszköznek a tartozéka', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eszkozkezelo_app.eszkoz', verbose_name='Mely eszköz tartozéka'),
        ),
        migrations.AlterField(
            model_name='kepek',
            name='kep',
            field=models.ImageField(blank=True, help_text='Az eszközről készült fotó', null=True, upload_to='kepek/', verbose_name='Kép'),
        ),
        migrations.AlterField(
            model_name='kepek',
            name='keszitesIdeje',
            field=models.DateField(verbose_name='Kép készítés ideje'),
        ),
        migrations.AlterField(
            model_name='mozgas',
            name='mozgasIdo',
            field=models.DateField(default=datetime.date.today, help_text='Az esköz mozgatásának pontos ideje', verbose_name='Mozgás ideje'),
        ),
        migrations.AlterField(
            model_name='mozgastipusok',
            name='megnevezes',
            field=models.CharField(help_text='Az eszköz kiadásra vagy bevételezésre sbt került', max_length=50, verbose_name='Mozgástípusok'),
        ),
        migrations.AlterField(
            model_name='szemely',
            name='aktiv',
            field=models.BooleanField(default=True, help_text='Az adott személyre kiadható-e eszköz', verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='szemely',
            name='email',
            field=models.EmailField(help_text='Kérjük, adja meg az érvényes e-mail címet', max_length=254, verbose_name='Email cím'),
        ),
        migrations.AlterField(
            model_name='szemely',
            name='nev',
            field=models.CharField(help_text='A személy teljes neve', max_length=60, verbose_name='Személy neve'),
        ),
        migrations.AlterField(
            model_name='tipus',
            name='megnevezes',
            field=models.CharField(help_text='A típus pontos megnevezése', max_length=60, verbose_name='Típus neve'),
        ),
    ]
