# Generated by Django 4.2.20 on 2025-05-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eszkozkezelo_app', '0004_remove_beszallito_beszallitocontatkt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eszkoz',
            name='kep_id',
        ),
        migrations.AddField(
            model_name='kepek',
            name='eszkoz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kepek', to='eszkozkezelo_app.eszkoz', verbose_name='Eszkoz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beszallito',
            name='beszallitoNev',
            field=models.CharField(help_text='Beszállító elnevezése', max_length=50, verbose_name='Beszállító neve'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='beszallito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.beszallito', verbose_name='Beszallító'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='holvanId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.szemely', verbose_name='Hol van'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='tipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.tipus', verbose_name='Típus'),
        ),
    ]
