# Generated by Django 4.2.20 on 2025-05-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eszkozkezelo_app', '0005_remove_eszkoz_kep_id_kepek_eszkoz_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mozgas',
            name='eszkoz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mozgastortenet', to='eszkozkezelo_app.eszkoz', verbose_name='Eszköz'),
            preserve_default=False,
        ),
    ]
