# Generated by Django 4.2.20 on 2025-05-16 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eszkozkezelo_app', '0006_mozgas_eszkoz'),
    ]

    operations = [
        migrations.CreateModel(
            name='EszkozParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100, verbose_name='Paraméter neve')),
                ('tipus', models.CharField(choices=[('SZ', 'Szöveg'), ('INT', 'Egész szám'), ('FLOAT', 'Tört szám'), ('BOOL', 'Logikai (igen/nem)'), ('DATE', 'Dátum')], max_length=10, verbose_name='Paraméter típusa')),
            ],
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='beszerzesiIdo',
            field=models.DateField(default=datetime.date.today, help_text='Beszerzés időpontja ( asz eszköz felvétel időpontja)', verbose_name='Beszerzés ideje'),
        ),
        migrations.CreateModel(
            name='TipusParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.eszkozparameter')),
                ('tipus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.tipus')),
            ],
        ),
        migrations.CreateModel(
            name='EszkozParameterErtek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ertek_szoveg', models.TextField(blank=True, null=True)),
                ('ertek_szam', models.FloatField(blank=True, null=True)),
                ('ertek_logikai', models.BooleanField(blank=True, null=True)),
                ('ertek_datum', models.DateField(blank=True, null=True)),
                ('eszkoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterek', to='eszkozkezelo_app.eszkoz')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eszkozkezelo_app.eszkozparameter')),
            ],
        ),
    ]
