# Generated by Django 4.2.20 on 2025-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eszkozkezelo_app', '0007_eszkozparameter_alter_eszkoz_beszerzesiido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eszkozparameter',
            name='leiras',
            field=models.TextField(blank=True, help_text='Rövid leírás a paraméterről', null=True, verbose_name='Leírás'),
        ),
        migrations.AddField(
            model_name='eszkozparameter',
            name='mertekegyseg',
            field=models.CharField(blank=True, help_text='Opcionális mértékegység a paraméterhez', max_length=20, null=True, verbose_name='Mértékegység'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='selejtezesiIdo',
            field=models.DateField(help_text='Mikor került selejtezésre az esköz', verbose_name='Selejtezési idő'),
        ),
    ]
