# Generated by Django 4.2.20 on 2025-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eszkozkezelo_app', '0008_eszkozparameter_leiras_eszkozparameter_mertekegyseg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eszkoz',
            name='leltari_szam',
            field=models.CharField(default=1, help_text='Automatikusan generált leltári szám', max_length=10, unique=True, verbose_name='Leltári szám'),
            preserve_default=False,
        ),
    ]
