# Generated by Django 4.2.20 on 2025-07-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eszkozkezelo_app', '0009_eszkoz_leltari_szam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eszkoz',
            name='leltari_szam',
            field=models.CharField(blank=True, help_text='Automatikusan generált leltári szám', max_length=10, unique=True, verbose_name='Leltári szám'),
        ),
        migrations.AlterField(
            model_name='eszkoz',
            name='selejtezesiIdo',
            field=models.DateField(blank=True, help_text='Mikor került selejtezésre az esköz', null=True, verbose_name='Selejtezési idő'),
        ),
    ]
